
export type Product = {
  id: string;
  name: string;
  description: string;
  image: string;
  aiHint: string;
  price: number;
  tags: string[];
};

export const products: Product[] = [
  {
    id: 'prod_001',
    name: 'Microsurfacing CH-17',
    description: 'Lapisan aus tipis untuk jalan dengan lalu lintas berat. Meningkatkan kekesatan dan daya tahan permukaan.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'road resurfacing',
    price: 1700000,
    tags: ['Perawatan Jalan', 'Microsurfacing'],
  },
  {
    id: 'prod_002',
    name: 'Microsurfacing CH-15',
    description: 'Solusi pelapisan ulang untuk jalan dengan lalu lintas sedang. Cepat kering dan memulihkan profil jalan.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'road paving',
    price: 1500000,
    tags: ['Perawatan Jalan', 'Microsurfacing'],
  },
  {
    id: 'prod_003',
    name: 'Microsurfacing CH-19',
    description: 'Varian premium untuk perkerasan jalan tol dan arteri primer. Memberikan performa jangka panjang.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'highway construction',
    price: 1900000,
    tags: ['Perawatan Jalan', 'Microsurfacing'],
  },
  {
    id: 'prod_004',
    name: 'Microsurfacing CH-21',
    description: 'Campuran khusus untuk iklim tropis, tahan terhadap deformasi akibat suhu tinggi.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'asphalt texture',
    price: 2100000,
    tags: ['Perawatan Jalan', 'Microsurfacing'],
  },
  {
    id: 'prod_005',
    name: 'Microsurfacing CH-23',
    description: 'Formula agregat halus untuk penutupan retak rambut dan peremajaan permukaan jalan kota.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'city road repair',
    price: 2300000,
    tags: ['Perawatan Jalan', 'Microsurfacing'],
  },
  {
    id: 'prod_006',
    name: 'Sabda Seal CH-27',
    description: 'Bahan pengisi celah sambungan berbasis aspal yang dimodifikasi, fleksibel dan tahan cuaca.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'road sealant',
    price: 650000,
    tags: ['Perawatan Jalan', 'Sealant'],
  },
  {
    id: 'prod_007',
    name: 'Sabda Seal CH-29',
    description: 'Sealant premium untuk jembatan dan struktur beton. Elastisitas tinggi untuk menahan pergerakan.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'concrete crack sealant',
    price: 750000,
    tags: ['Perawatan Jalan', 'Sealant', 'Waterproofing'],
  },
  {
    id: 'prod_008',
    name: 'Sabda Seal CH-31',
    description: 'Varian sealant yang dapat diaplikasikan pada suhu rendah, cocok untuk area pegunungan.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'sealant application',
    price: 800000,
    tags: ['Perawatan Jalan', 'Sealant'],
  },
  {
    id: 'prod_009',
    name: 'Microseal CH-25',
    description: 'Lapisan pelindung ultra-tipis untuk meremajakan permukaan aspal dan melindunginya dari oksidasi.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'asphalt sealing',
    price: 1250000,
    tags: ['Perawatan Jalan', 'Waterproofing'],
  },
  {
    id: 'prod_010',
    name: 'Coating CH-34',
    description: 'Pelapis pelindung berwarna untuk area parkir, jalur sepeda, dan lapangan olahraga. Anti selip dan tahan UV.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'colored asphalt',
    price: 950000,
    tags: ['Marka Jalan', 'Coating'],
  },
  {
    id: 'prod_011',
    name: 'Coldplast CH-33',
    description: 'Bahan marka jalan dua komponen yang diaplikasikan dingin, sangat tahan lama untuk area lalu lintas tinggi.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'road marking application',
    price: 1100000,
    tags: ['Marka Jalan'],
  },
  {
    id: 'prod_012',
    name: 'Ecobeton (Chrono)',
    description: 'Aditif untuk mempercepat waktu pengeringan beton tanpa mengurangi kekuatan akhir.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'concrete pouring',
    price: 2500000,
    tags: ['Penguatan Struktur', 'Ecobeton'],
  },
  {
    id: 'prod_013',
    name: 'Ecobeton (Pavishield)',
    description: 'Pelindung permukaan beton yang menembus ke dalam, tahan terhadap air, minyak, dan bahan kimia.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'concrete protection',
    price: 2800000,
    tags: ['Penguatan Struktur', 'Ecobeton', 'Waterproofing'],
  },
  {
    id: 'prod_014',
    name: 'Ecobeton (Vetrofluid)',
    description: 'Cairan silikat untuk membuat beton menjadi kedap air secara permanen dan tahan abrasi.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'concrete floor',
    price: 3100000,
    tags: ['Penguatan Struktur', 'Ecobeton', 'Waterproofing'],
  },
  {
    id: 'prod_015',
    name: 'GEOne',
    description: 'Material geotekstil non-anyaman untuk stabilisasi tanah, perkuatan, dan sistem drainase.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'geotextile fabric',
    price: 850000,
    tags: ['Penguatan Struktur'],
  },
  {
    id: 'prod_016',
    name: 'Coldmix CH-28',
    description: 'Aspal dingin premium siap pakai untuk perbaikan darurat. Daya rekat tinggi dan tahan lama.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'asphalt patch',
    price: 400000,
    tags: ['Perawatan Jalan', 'Coldmix'],
  },
  {
    id: 'prod_017',
    name: 'Coldmix CH-24',
    description: 'Aspal dingin ekonomis untuk penambalan jalan sekunder dan perumahan. Mudah diaplikasikan.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'pothole repair',
    price: 320000,
    tags: ['Perawatan Jalan', 'Coldmix'],
  },
  {
    id: 'prod_018',
    name: 'S.A.M.I Waterproofing CH-13',
    description: 'Membran interlayer anti retak dan kedap air untuk jembatan dan jalan layang.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'waterproofing membrane',
    price: 1800000,
    tags: ['Waterproofing'],
  },
  {
    id: 'prod_019',
    name: 'Marka CH-32',
    description: 'Cat termoplastik berperforma tinggi untuk marka jalan. Reflektifitas tinggi dan cepat kering.',
    image: 'https://placehold.co/600x600.png',
    aiHint: 'road marking paint',
    price: 750000,
    tags: ['Marka Jalan'],
  }
];
